Repository Lissy93/dashy, pull requests merged in 2021-11, with the labels that each got.

#319 [FIX] UI Bug Fixes for Interactive Editor + Style Refactor
  .github/.lycheeexclude
  .github/CHANGELOG.md
  .github/pr-badge.yml
  .github/workflows/docs-link-checker.yml
  docs/status-indicators.md
  package.json
  src/assets/locales/en.json
  src/components/InteractiveEditor/EditModeSaveMenu.vue
  src/components/LinkItems/Collapsable.vue
  src/components/LinkItems/Item.vue
  src/components/PageStrcture/Nav.vue
  src/components/Settings/CustomThemeMaker.vue
  src/styles/color-palette.scss
  src/styles/color-themes.scss
  src/utils/defaults.js
  src/views/Home.vue
Labels: 🦋 Bug Fix

#322 [REFACTOR] Minor Code Updates
  docs/showcase.md
  src/assets/locales/en.json
  src/components/Configuration/AppInfoModal.vue
  src/components/Configuration/CloudBackupRestore.vue
  src/components/Configuration/ConfigContainer.vue
  src/components/Configuration/CustomCss.vue
  src/components/Configuration/JsonEditor.vue
  src/components/InteractiveEditor/EditModeSaveMenu.vue
  src/components/InteractiveEditor/ExportConfigMenu.vue
  src/components/Settings/ThemeSelector.vue
  src/store.js
  src/styles/color-themes.scss
  src/utils/ErrorHandler.js
  src/utils/StoreMutations.js
  src/views/Login.vue
Labels: 🚚 Refactor

#326 [ARCHITECTURE] Performance and Speed Improvements
  .env
  .github/CHANGELOG.md
  .github/workflows/apply-done-label.yml
  .github/workflows/assign-reviewer.yml
  .github/workflows/auto-rebase-pr.yml
  .github/workflows/auto-tag-pr.yml
  .github/workflows/broadcast-message.yml
  .github/workflows/build-app.yml
  .github/workflows/check-duplicate-issues.yml
  .github/workflows/check-merge-conflicts.yml
  .github/workflows/close-incomplete-issues.yml
  .github/workflows/close-stale-issues.yml
  .github/workflows/code-spell-check.yml
  .github/workflows/domain-expirey-check.yml
  .github/workflows/generate-credits.yml
  .github/workflows/issue-spam-control.yml
  .github/workflows/issue-translator.yml
  .github/workflows/label-top-issues.yml
  .github/workflows/manage-pending-labels-closed.yml
  .github/workflows/manage-pending-labels.yml
  .github/workflows/mind-your-language.yml
  .github/workflows/pr-labler.yml
  .github/workflows/raise-issue-from-todo.yml
  .github/workflows/release-commenter.yml
  .github/workflows/repo-visualization.yml
  .github/workflows/save-repo-analytics.yml
  .github/workflows/wiki-sync.yml
  docs/icons.md
  docs/management.md
  package.json
  public/initialization.html
  server.js
  services/ssl-server.js
  src/components/LinkItems/ItemIcon.vue
  src/router.js
  src/utils/defaults.js
  yarn.lock
Labels: 🏗️ Architectural Changes

#330 configuring.md: fix keycloak type mismatch
  docs/configuring.md
Labels: 📕 Docs

#332 Update README.md
  README.md
Labels: 📕 Docs

#331 [REFACTOR] Updates favicon fetching and docs
  README.md
  docs/icons.md
  package.json
  src/components/Settings/SettingsContainer.vue
  src/utils/defaults.js
  yarn.lock
Labels: 🚚 Refactor

#325 [DRAFT] Update French translation
  src/assets/locales/fr.json
Labels: 🌐 Language

#334 Updated Slovenian Locale
  src/assets/locales/sl.json
Labels: 🌐 Language
