Repository Lissy93/dashy, pull requests merged in 2021-12, with the labels that each got.

#237 [FEATURE] Adds option to Remember Me for a long time
  package.json
  src/assets/locales/en.json
  src/assets/locales/fr.json
  src/views/Login.vue
Labels: ✨ New Feature, 🟩 PR - Small

#354 [FEATURE] Case-insensitive item sorting
  src/components/LinkItems/Section.vue
Labels: ✨ New Feature

#355 Added initial Swedish translation
  README.md
  src/assets/locales/sv.json
  src/utils/languages.js
Labels: 🌐 Language

#369 Docker Multi-Arch GH-Action
  .github/workflows/docker-image.yml
Labels: 🏗️ Architectural Changes

#388 [FIX] Couple of minor issues
  .github/CHANGELOG.md
  docs/configuring.md
  docs/icons.md
  package.json
  src/App.vue
  src/assets/locales/en.json
  src/components/InteractiveEditor/EditItem.vue
  src/store.js
  src/utils/ConfigHelpers.js
  src/utils/ConfigSchema.json
  src/utils/defaults.js
Labels: 🦋 Bug Fix
