Repository Lissy93/dashy, pull requests merged in 2022-09, with the labels that each got.

#875 :sparkles: Adds state option for PublicHolidays widget
  docs/widgets.md
  src/components/Widgets/PublicHolidays.vue
Labels: ✨ New Feature

#891 Removed build watch and tini from container run-time
  Dockerfile
Labels: 🏗️ Architectural Changes

#887 with built in auth, if user adds a capital letter to username they ca…
  src/utils/Auth.js
Labels: 🦋 Bug Fix

#880 Fix widget GlDiskSpace 401 unauth
  src/components/Widgets/GlDiskSpace.vue
Labels: 🦋 Bug Fix

#862 Fix issue #856
  src/components/Widgets/Clock.vue
Labels: 🦋 Bug Fix

#874 ⬆️ Updates optional external icons
  src/utils/defaults.js
Labels: 🚚 Refactor

#895 Add Slovak language
  README.md
  src/assets/locales/sk.json
  src/utils/languages.js
Labels: 🌐 Language

#871 IframeWidget min-height reduce to 80px
  src/components/Widgets/IframeWidget.vue
Labels: 🦋 Bug Fix, 🔀 Ready for Merge

#899 Update Spanish Translation
  src/assets/locales/es.json
Labels: 🌐 Language
