Repository Lissy93/dashy, pull requests merged in 2022-05, with the labels that each got.

#625 Finish PT translation
  src/assets/locales/pt.json
Labels: 🌐 Language

#617 [FEATURE] Multi-Page Support
  .github/CHANGELOG.md
  .github/LATEST_CHANGELOG.md
  README.md
  docs/configuring.md
  docs/pages-and-sections.md
  docs/readme.md
  docs/theming.md
  docs/troubleshooting.md
  package.json
  public/index.html
  server.js
  services/save-config.js
  src/App.vue
  src/assets/interface-icons/config-pages.svg
  src/assets/locales/en.json
  src/components/Configuration/ConfigContainer.vue
  src/components/Configuration/JsonEditor.vue
  src/components/InteractiveEditor/EditModeSaveMenu.vue
  src/components/InteractiveEditor/EditMultiPages.vue
  src/components/InteractiveEditor/SaveCancelButtons.vue
  src/components/LinkItems/ItemIcon.vue
  src/components/PageStrcture/Footer.vue
  src/components/PageStrcture/Nav.vue
  src/components/Settings/ConfigLauncher.vue
  src/components/Settings/ViewSwitcher.vue
  src/mixins/ConfigSaving.js
  src/mixins/HomeMixin.js
  src/router.js
  src/store.js
  src/styles/color-themes.scss
  src/styles/schema-editor.scss
  src/utils/ConfigAccumalator.js
  src/utils/ConfigHelpers.js
  src/utils/ConfigSchema.json
  src/utils/InitServiceWorker.js
  src/utils/SectionHelpers.js
  src/utils/StoreMutations.js
  src/utils/defaults.js
Labels: ✨ New Feature

#663 [FIX] User Suggestions & Bug Fixes
  .github/CHANGELOG.md
  .github/LATEST_CHANGELOG.md
  .github/workflows/docker-build-publish.yml
  README.md
  docs/authentication.md
  docs/configuring.md
  docs/pages-and-sections.md
  docs/troubleshooting.md
  docs/widgets.md
  package.json
  src/assets/interface-icons/section-expand-collapse.svg
  src/assets/locales/en.json
  src/components/LinkItems/Collapsable.vue
  src/components/LinkItems/Section.vue
  src/components/LinkItems/SectionContextMenu.vue
  src/components/Settings/SettingsContainer.vue
  src/components/Settings/ThemeSelector.vue
  src/components/Widgets/BlacklistCheck.vue
  src/components/Widgets/Clock.vue
  src/components/Widgets/RssFeed.vue
  src/components/Widgets/SportsScores.vue
  src/mixins/HomeMixin.js
  src/mixins/ItemMixin.js
  src/mixins/WidgetMixin.js
  src/router.js
  src/store.js
  src/styles/color-themes.scss
  src/utils/ConfigAccumalator.js
  src/utils/ConfigSchema.json
  src/utils/KeycloakAuth.js
  src/utils/defaults.js
  src/views/Home.vue
Labels: 🦋 Bug Fix

#671 Add HOST environment
  server.js
Labels: 🦋 Bug Fix

#684 Add dr460nf1r3's Dashy
  docs/showcase.md
  docs/showcase/13-dragons-lair.png
Labels: 💯 Showcase
