Repository Lissy93/dashy, pull requests merged in 2022-07, with the labels that each got.

#779 [FEATURE] Option for labeled widgets
  docs/configuring.md
  docs/widgets.md
  src/components/LinkItems/Collapsable.vue
  src/components/LinkItems/ItemIcon.vue
  src/components/Widgets/WidgetBase.vue
Labels: ✨ New Feature

#784 Update de.json
  src/assets/locales/de.json
Labels: 🌐 Language

#788 Fix storage calculation
  src/components/Widgets/GlDiskSpace.vue
Labels: 🦋 Bug Fix

#790 Feature/widget Sabnzbd
  docs/widgets.md
  src/components/Widgets/Sabnzbd.vue
  src/components/Widgets/WidgetBase.vue
Labels: ✨ New Feature

#813 [REFACTOR] Lint, error catching and translations for Gluetun Status Widget
  docs/widgets.md
  src/assets/locales/en.json
  src/components/Widgets/GluetunStatus.vue
Labels: 🚚 Refactor
