Repository Lissy93/dashy, pull requests merged in 2022-10, with the labels that each got.

#945 Update sv.json + add danish locale
  src/assets/locales/da.json
  src/assets/locales/sv.json
  src/utils/languages.js
Labels: 🌐 Language

#964 Fixed comment describing healthcheck
  services/healthcheck.js
Labels: 🚚 Refactor

#966 [FEATURE] Adds option for default icon
  docs/configuring.md
  docs/icons.md
  src/components/LinkItems/Item.vue
  src/components/LinkItems/Section.vue
  src/utils/ConfigSchema.json
Labels: ✨ New Feature

#926 Allow favicons for subdomains
  src/components/LinkItems/ItemIcon.vue
Labels: 🦋 Bug Fix, ⚰️ Stale
