Repository Lissy93/dashy, pull requests merged in 2023-12, with the labels that each got.

#1405 [Docs] Improved minor errors in development-guides.md file
  docs/development-guides.md
Labels: 📕 Docs

#1359 Update zh-TW.json
  src/assets/locales/zh-TW.json
Labels: 🌐 Language

#1352 Fix nextcloud widgets reference
  docs/widgets.md
Labels: 🦋 Bug Fix

#1418 Update the Japanese translation
  src/assets/locales/ja.json
Labels: 🌐 Language
