Repository Lissy93/dashy, pull requests merged in 2023-01, with the labels that each got.

#1030 Update German (de) locale
  src/assets/locales/de.json
Labels: 🌐 Language

#1039 Allow multiple Project Keys for HealthChecks
  docs/widgets.md
  src/components/Widgets/HealthChecks.vue
Labels: 🔀 Ready for Merge, 🚚 Refactor

#1037 Drone io widget
  docs/widgets.md
  src/components/Widgets/DroneCi.vue
  src/components/Widgets/WidgetBase.vue
Labels: ✨ New Feature

#1047 Added Mvg Widget
  docs/widgets.md
  src/components/Widgets/Mvg.vue
  src/components/Widgets/MvgConnection.vue
  src/components/Widgets/WidgetBase.vue
  src/utils/defaults.js
Labels: ✨ New Feature

#1048 Fix HealthChecks linting errors
  src/components/Widgets/HealthChecks.vue
Labels: 🚫 Merge Conflicts
