Repository Lissy93/dashy, pull requests merged in 2023-02, with the labels that each got.

#1069 Update fr.json
  src/assets/locales/fr.json
Labels: 🌐 Language

#1066 :bug: Add trailing slash to quick fix #1064
  src/components/Workspace/SideBar.vue
Labels: 🦋 Bug Fix

#1088 added: new language (Turkish).
  src/assets/locales/tr.json
Labels: 🌐 Language

#1107 Add new language (Bengali)
  src/assets/locales/bn.json
Labels: 🌐 Language

#1121 [TRANSLATIONS] Links the Turkish and Bengali locales, and updates lang docs
  README.md
  src/components/Widgets/MvgConnection.vue
  src/utils/languages.js
Labels: 📕 Docs, 🌐 Language

#1123 [FIX] Counter for most-used + last-used, and lint warns
  src/components/Widgets/Clock.vue
  src/components/Widgets/Mvg.vue
  src/mixins/ItemMixin.js
Labels: 🦋 Bug Fix

#1124 [FIX] Updates the endpoint for currency flags
  src/utils/MiscHelpers.js
Labels: 🦋 Bug Fix
